name: dangerjs-check-action
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: danger
        run: npx danger ci
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}